### ISSUE TITLE
io/timeout implementing a simple ArrowLogsServer

### ISSUE THREAD

**Issue by metalmatze** [open-telemetry/otel-arrow#118]
Hey, thank you for this cool project!

I'm playing around with a simple receiver for logs right now. 
The stream never receives meaningful data and always returns with an `i/o timeout` error (line 26). 

As far as I could troubleshoot the problem, it could be related to the compression of the incoming requests.
I've tried to run the bridge with `compression: none` but nothing changes. 

Is there a recommended way to use the otel-arrow collector as a library? For now, I'm only interested in the logging parts, which is why the entirety of the collector seems overkill. 

```go
package ingest

import (
	"errors"
	"io"

	otelarrowv1 "github.com/open-telemetry/otel-arrow/api/experimental/arrow/v1"
	arrowRecord "github.com/open-telemetry/otel-arrow/pkg/otel/arrow_record"
)

func (i *Ingester) ArrowLogs(serverStream otelarrowv1.ArrowLogsService_ArrowLogsServer) error {
	var count int
	for {
		batchArrowRecords, err := serverStream.Recv()
		count++

		if err != nil {
			if err == io.EOF {
				status := &otelarrowv1.BatchStatus{}
				status.StatusCode = otelarrowv1.StatusCode_CANCELED
				err = serverStream.Send(status)
				if err != nil {
					return err
				}
				return nil
			}
			return err
		}

		status := &otelarrowv1.BatchStatus{
			BatchId: batchArrowRecords.GetBatchId(),
		}
		if err == nil {
			status.StatusCode = otelarrowv1.StatusCode_OK
		} else {
			status.StatusMessage = err.Error()
			if errors.Is(err, arrowRecord.ErrConsumerMemoryLimit) {
				status.StatusCode = otelarrowv1.StatusCode_RESOURCE_EXHAUSTED
			} else {
				status.StatusCode = otelarrowv1.StatusCode_UNAVAILABLE
			}
		}

		err = serverStream.Send(status)
		if err != nil {
			return err
		}
	}
}
```

Let me know if you need additional information. 
Thanks for taking a look!

**Comment by lquerel** [comment]
In theory, it is entirely feasible, but currently, the code of the OTel Arrow receiver relies on components from the collector. There isn't, at the moment, an independent library from the collector planned in the near future. The current focus is the integration of the OTel Arrow Receiver / Exporter pair in the OpenTelemetry contrib portal. 
@jmacd, any things/suggestions to add to this?

**Comment by jmacd** [comment]
@metalmatze Thanks for trying this out.

I have code using the `otelarrowexporter` component directly for spans and metrics, here:

https://github.com/lightstep/otel-launcher-go/tree/main/lightstep/sdk/trace/exporters/otlp/otelcol
https://github.com/lightstep/otel-launcher-go/tree/main/lightstep/sdk/metric/exporters/otlp/otelcol

On the surface, what you're trying to do looks like a correct receiver body. I'm interested in knowing how you set up the other side and what it may be printing?

**Comment by jmacd** [comment]
Please re-open if we can help, thanks!
