### ISSUE TITLE
DataGenerator.FakeHistogram generates incorrect histograms

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/otel-arrow#261]
The (count of buckets) [must be](https://github.com/open-telemetry/opentelemetry-proto/blob/a76fe9dea26871e8a6c494024bc9927fe73b8142/opentelemetry/proto/metrics/v1/metrics.proto#L461) the (count of bounds)+1.

[Here](https://github.com/open-telemetry/otel-arrow/blob/7cceec5e8ca0c0a0ee8be4806ced19e49e96778b/pkg/datagen/metrics.go#L739) in DataGenerator.FakeHistogram they are both set to 10.

**Comment by lquerel** [comment]
Thank you for reporting that. I will fix the issue asap.

**Comment by lquerel** [comment]
Fixed in release v0.29.0.
