### ISSUE TITLE
Should the Arrow components sever their version history with OTLP exporter/receiver

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/otel-arrow#43]
Until now, the Arrow components have been maintained as derivatives of the OTLP exporter and receiver. They aim to maintain drop-in configuration compatibility, to make upgrading to Arrow very easy for users. When using gRPC, Arrow-enabled clients can send Arrow or standard OTLP, which makes a seamless upgrade possible. Presently, it would be relatively easy to merge the Arrow components into the core. This merge would be more difficult without this shared history. Maintaining drop-in compatibility going forward is also easier this way, through [periodic re-synchronization with the original branch history](https://github.com/open-telemetry/otel-arrow-collector/issues/48).

However, this maintenance has a cost, and it may be time to abandon the shared history. Here are the downsides:

- Component code is less readable, because it retains OTLP-specific variable naming in most places. We can't apply janitorial changes because it will make merges harder in the future. (The code is largely unmodified from the OTLP components, with only new `internal/arrow` code added.)
- The receiver component includes an entire HTTP receiver, unmodified from the OTLP receiver. This is unnecessary baggage for the otelarrow exporter, unless we move to add HTTP support in the future. (Which has been requested.) In the present, it just means a lot of code unnecessarily duplicated with the core components.
- It leads to confusing validation logic, because the validation logic is shared w/ the HTTP aspect of the receiver component. [For example.](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26519/files/67aee1efde57a0a37108a25e2c99e4ab6c7f033d#r1319183062)

If we decided to abandon the version history, we could remove the HTTP receiver and clean up the code in a bunch of ways. This would make future compatibility with the OTLP Exporter/Receiver a more manual process.

**Comment by lquerel** [comment]
@jmacd I can see the benefit of separating these two pairs of receiver/exporter in the specific context of optimizing OTel internet traffic between two collectors whose configuration is perfectly known and controlled. However, the current approach seems more appropriate between clients and a collector because it is a context where the configurations of all these actors are more difficult to align uniformly. 
In my opinion, this separation is conceivable in phase 1 (current phase) but in my view, it will be necessary to be able to have this automatic fallback mechanism between OTLP and OTel Arrow in phase 2 for maximum flexibility (i.e. Client SDK supporting OTel Arrow and end-to-end support of OTel Arrow pipelines in the collector).

**Comment by jmacd** [comment]
Here's my opinion: the HTTP support is worth keeping, even though it looks extraneous, because if this protocol is a success we can expect users to want to use it directly over HTTP/2 streams. This allows us to advisers to simply replace their OTLP exporter and receiver with OTel Arrow components, period.

**Comment by codeboten** [comment]
As a user, I would find confusing being able to configure the HTTP protocol, but getting the benefits of arrow for it. In other words, I would rather see an error (ie. http not supported) than to have it quietly continue to work, but it's not doing what I expect it to.

**Comment by jmacd** [comment]
>  have it quietly continue to work, but it's not doing what I expect it to.

If the user is using an HTTP exporter, it will work the way HTTP exporters are expected to work.
If they are using a OTLP/gRPC exporter, it will work the way gRPC exporters are expected to work.
If they are using an OTel Arrow exporter, it will work ...

I'm not sure this is any more confusing than having the core OTLP receiver support two transports. If we leave HTTP support as it stands, then the upgrade from OTLP receiver to Arrow receiver is straightforward. If we don't, it's not. I'll have to give instructions like to replace this.

```
receivers:
  otlp:
    protocols:
      http: ...
      grpc: ...
```

with

```
receivers:
  otlp:
    protocols:
      http: ...
  otelarrow:
    protocols:
      grpc: ...
```

Here, now it will be confusing that `otelarrow` is the receiver for OTLP/gRPC which uses the same port. 

Another way to think about it is that OTel Arrow is just another form of OTLP, and we have a receiver here that can accept data in all three forms. Given the easier drop-in, the possibility of adding HTTP/OTel-Arrow in the future, and the existence of `otlpreceiver` with two transports already, and the loss of coordinated version history if we diverge too far, I think removing HTTP from otel-arrow is a net loss for the project.

**Comment by jmacd** [comment]
Have arrived at a decision to abandon or forget the shared version history and remove HTTP support from the OTel-Arrow receiver, to help unblock https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26491.

**Comment by jmacd** [comment]
This was decided. The early history has been archived, and we are independent now from the OTLP upstream.
